apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: mini-platform
rules:
  - apiGroups: ["", "apps", "batch", "networking.k8s.io"]
    resources: ["configmaps", "pods", "services", "deployments", "replicasets", "jobs", "cronjobs", "ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer
  namespace: mini-platform
rules:
  - apiGroups: ["", "apps", "batch", "networking.k8s.io"]
    resources: ["configmaps", "pods", "services", "deployments", "replicasets", "jobs", "cronjobs", "ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre
  namespace: mini-platform
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
