apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: mini-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: mini-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre
  namespace: mini-platform
